stages:
  - build
  - deploy

build:
  stage: build
  image: tetraweb/php:7.1
  before_script:
    - npm install --silent
    - npm install --global gulp-cli
  script:
    - gulp production

deploy_staging:
  stage: deploy
  image: tetraweb/php:7.1
  cache:
    paths:
      - node_modules/
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get -qq install rsync
    - npm install --silent
    - npm install --global gulp-cli
  script:
    - gulp production
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/stable-version.florianbrinkmann.de/wp-content/themes/photographus"
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/trunk-version.florianbrinkmann.de/wp-content/themes/photographus"
    - rsync -ravq -e ssh --exclude='.git/' --exclude=tests/ --exclude=node_modules/ --exclude=bin/ --exclude='.gitignore' --exclude=assets/css/scss/ --exclude='.gitlab-ci.yml' --exclude=gulpfile.js --exclude=package.json --exclude=assets/css/photographus.css.map --delete-excluded ./ fbndev@aries.uberspace.de:/var/www/virtual/fbndev/trunk-version.florianbrinkmann.de/wp-content/themes/photographus
    - rsync -ravq -e ssh --exclude='.git/' --exclude=tests/ --exclude=node_modules/ --exclude=bin/ --exclude='.gitignore' --exclude=assets/css/scss/ --exclude='.gitlab-ci.yml' --exclude=gulpfile.js --exclude=package.json --exclude=assets/css/photographus.css.map --delete-excluded ./ fbndev@aries.uberspace.de:/var/www/virtual/fbndev/stable-version.florianbrinkmann.de/wp-content/themes/photographus
    - rsync -ravq -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --delete-excluded ./ fbndev@aries.uberspace.de:/var/www/virtual/fbndev/html/wp-content/themes/photographus
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser"
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser-tmp"
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser/photographus"
    - ssh -p22 fbndev@aries.uberspace.de "mv /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser/photographus /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser-tmp/_old-photographus && cp -Rf /var/www/virtual/fbndev/html/wp-content/themes/photographus /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser/photographus"
    - ssh -p22 fbndev@aries.uberspace.de "rm -rf /var/www/virtual/fbndev/html/wp-content/themes-for-docblock-parser-tmp/_old-photographus"
    - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar --silent
    - chmod +x wp-cli.phar
    - mv wp-cli.phar /usr/bin/wp
    - wp parser create wp-content/themes-for-docblock-parser/ --user=florian --url=dev.florianbrinkmann.de --allow-root --ssh=fbndev@aries.uberspace.de/var/www/virtual/fbndev/html/ --quiet
    - wp parser create wp-content/themes-for-docblock-parser/ --user=florian --url=dev.florianbrinkmann.de/en --allow-root --ssh=fbndev@aries.uberspace.de/var/www/virtual/fbndev/html/ --quiet
  environment:
    name: staging
  only:
    - staging

deploy_production:
  stage: deploy
  image: tetraweb/php:7.1
  cache:
    paths:
      - node_modules/
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get -qq install rsync zip
    - npm install --silent
    - npm install --global gulp-cli
  script:
    - gulp production
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes/_tmp-photographus"
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes/photographus"
    - rsync -ravq -e ssh --exclude='.git/' --exclude=node_modules/ --exclude=bin/ --exclude='.gitignore' --exclude=assets/css/scss/ --exclude='.gitlab-ci.yml' --exclude=gulpfile.js --exclude=package.json --exclude=assets/css/photographus.css.map --delete-excluded ./ fbn@horologium.uberspace.de:/var/www/virtual/fbn/html/wp-content/themes/_tmp-photographus
    - ssh -p22 fbn@horologium.uberspace.de "mv /var/www/virtual/fbn/html/wp-content/themes/photographus /var/www/virtual/fbn/html/wp-content/themes/_old-photographus && mv /var/www/virtual/fbn/html/wp-content/themes/_tmp-photographus /var/www/virtual/fbn/html/wp-content/themes/photographus"
    - ssh -p22 fbn@horologium.uberspace.de "rm -rf /var/www/virtual/fbn/html/wp-content/themes/_old-photographus"
    - ssh -p22 fbn@horologium.uberspace.de "cd /var/www/virtual/fbn/html/wp-content/themes/ && zip -r photographus.zip photographus/"
    - ssh -p22 fbn@horologium.uberspace.de "mv /var/www/virtual/fbn/html/wp-content/themes/photographus.zip /var/www/virtual/fbn/woocommerce-downloads/photographus.zip"
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser"
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser-tmp"
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser/photographus"
    - ssh -p22 fbn@horologium.uberspace.de "mv /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser/photographus /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser-tmp/_old-photographus && cp -Rf /var/www/virtual/fbn/html/wp-content/themes/photographus /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser/photographus"
    - ssh -p22 fbn@horologium.uberspace.de "rm -rf /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser-tmp/_old-photographus"
    - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar --silent
    - chmod +x wp-cli.phar
    - mv wp-cli.phar /usr/bin/wp
    - wp parser create wp-content/themes-for-docblock-parser/ --user=florian --url=florianbrinkmann.com --allow-root --ssh=fbn@horologium.uberspace.de/var/www/virtual/fbn/html/ --quiet
    - wp parser create wp-content/themes-for-docblock-parser/ --user=florian --url=florianbrinkmann.com/en --allow-root --ssh=fbn@horologium.uberspace.de/var/www/virtual/fbn/html/ --quiet
  environment:
    name: production
  only:
    - master
